# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(702, 751)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.videoButton = QtWidgets.QPushButton(self.centralwidget)
        self.videoButton.setGeometry(QtCore.QRect(20, 620, 171, 61))
        self.videoButton.setObjectName("videoButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 661, 551))
        self.groupBox.setObjectName("groupBox")
        self.videoLabel = QtWidgets.QLabel(self.groupBox)
        self.videoLabel.setGeometry(QtCore.QRect(10, 30, 641, 511))
        self.videoLabel.setText("")
        self.videoLabel.setObjectName("videoLabel")
        self.videoLabel.setAlignment(Qt.AlignCenter)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(200, 570, 481, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.resultLable = QtWidgets.QLabel(self.groupBox_2)
        self.resultLable.setGeometry(QtCore.QRect(10, 20, 461, 121))
        self.resultLable.setText("")
        self.resultLable.setObjectName("resultLable")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "跑步姿态分析系统"))
        self.videoButton.setText(_translate("MainWindow", "选择视频"))
        self.groupBox.setTitle(_translate("MainWindow", "结果显示"))
        self.groupBox_2.setTitle(_translate("MainWindow", "结果分析及改进建议"))
